version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: smartcity_network
    ports:
      - "7070:80"  
    networks:
      - proxy_network

networks:
  proxy_network:
    driver: bridge